### ISSUE TITLE
user jenkins for docker commands

### ISSUE THREAD

**Issue by herau** [evarga/docker-images#9]
I try your slave but i can't run any docker commands.
i have this kind of message 
`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

How you can execute docker commands whereas the docker container only contains the `jenkins` user ? 
Docker need a root user to be able to run docker commands right ?

my docker-compose file:

```
version: '2'
services:
  master:
    user: root
    image: jenkinsci/jenkins
    links:
      - slave-docker
    environment:
      - JAVA_OPTS=-Duser.timezone=Europe/Paris
    volumes:
      - ./data:/var/jenkins_home
    ports:
      - "50000:50000"
      - "8080:8080"
  slave-docker:
    image: evarga/jenkins-slave
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #  static binay of docker
      - /home/data/docker/bin/docker:/bin/docker
```
In Jenkins i have created a slave 

![screen shot 2016-08-05 at 11 57 27 am](https://cloud.githubusercontent.com/assets/2950666/17433258/f1303512-5b03-11e6-9739-1d31a3bc6dce.png)
